- name: Pull and Run docker image
  hosts: all
  become: yes
  tasks:
    - name: copy docker compose file from folder to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./
    - name: name it
      shell: docker-compose up -d
